title: Syed Ghazali # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>

  <p align="justify">
  # TO BE FILLED
  <br><br>
  </p>
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-9HRE7S2T9J # your Google Analytics tracking ID here
